application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "denis.rodionov"
  password: ""
  database_name: "opusclassical"
  require_ssl: false
redis_uri: "redis://127.0.0.1:6379"